version: '3.8'

services:
  url-db:
    image: postgres:13.1
    restart: always
    tty: true
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: url-detection
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    container_name: url-db

  url-crawler:
    image: liu8613789/url-crawler
    restart: always
    tty: true
    env_file:
      - url_crawler.env
    volumes:
      - ./log/crawler:/var/www/html/url_crawler/log/
    container_name: url-crawler
